name: Dispatch After Merge

on:
  push:
    branches:
      - main

jobs:
  dispatch-to-websites:
    name: Dispatch to All Websites
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch to Kerzendorf Lab Website
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.RESEARCH_AND_NEWS }}" \
            -H "Accept: application/vnd.github+json" \
            -H "Content-Type: application/json" \
            -d '{ "event_type": "repo-push" }' \
            https://api.github.com/repos/kerzendorf-lab/groupwebsite_generator/dispatches

      - name: Dispatch to Tardis-org-data
        run: |
          curl -X POST \
          -H "Authorization: Bearer ${{ secrets.RESEARCH_AND_NEWS }}" \
          -H "Accept: application/vnd.github+json" \
          -H "Content-Type: application/json" \
          -d '{ "event_type": "repo-push" }' \
          https://api.github.com/repos/tardis-sn/tardis-org-data/dispatches

      - name: Dispatch to DTI website generator
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.RESEARCH_AND_NEWS }}" \
            -H "Accept: application/vnd.github+json" \
            -H "Content-Type: application/json" \
            -d '{ "event_type": "repo-push" }' \
            https://api.github.com/repos/deepthought-initiative/dtiwebsite_generator/dispatches
