name: Validate PR Article

on:
  pull_request:
    branches:
      - main

jobs:
  validating-article:
    name: Validate Article
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install --upgrade pip jupyter pandas

      - name: Run Validator Notebook
        run: |
          jupyter nbconvert --to python validate.ipynb
          python3 validate.py > validation_output.txt
          cat validation_output.txt
          grep -q "VALIDATION SUCCESSFUL" validation_output.txt
